webapp/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about')
]

webapp/webapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('clubs/', include('clubs.urls')),
    path('news/', include('news.urls')),
    path('auth/', include('authorization.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/main/models.py
from django.db import models

# Create your models here.

webapp/news/models.py
from django.db import models


class Articles(models.Model):
    title = models.CharField('Название', max_length=100)
    anons = models.CharField('Анонс', max_length=250)
    full_text = models.TextField('Статья')
    date = models.DateTimeField('Дата публикации')

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return f'/news/{self.id}'

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'

webapp/main/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    data = {
        'title': 'Главная страница',
        'description': 'Наш сайт предоставляет информацию о различных футбольных лигах со всего мира. Посетители могут найти расписание матчей, результаты игр, информацию о командах и игроках, текущие таблицы лиг, а также новости и статистику. Сайт также может предоставлять возможность регистрации пользователей, подписки на уведомления о матчах и многое еще будет.'
    }
    return render(request, 'main/index.html', data)


def about(request):
    return render(request, 'main/about.html')

webapp/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block title %}Про нас{% endblock %}

{% block content %}
    <div class="features">
        <h1>Про нас</h1>
        <p>Тестовая заглушка лдватьпмлдвтплдвьмлдкоптжлдкывмиьлыкежершщжтлдвадлжьидерошщекльдкылеьрклдdfsgiojrdfeigdfklgmrtimlkfdm</p>
        <button class="btn btn-danger">Просто нажми</button>
    </div>
{% endblock %}

webapp/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="features">
        {% include 'main/messages.html' %}
        {% if user.is_authenticated %}
            <h3 style="text-align: left">Здравствуйте, {{user.username}}</h3>
        {% endif %}
        <h1 style="margin-top: 50px">{{ title }}</h1>
        <p class="description">{{description}}</p>
        <button class="btn btn-warning">На страницу про нас</button>
    </div>
{% endblock %}

webapp/main/templates/main/layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} </title>
    {% include 'main/fragments/links_css.html' %}
    {% block links %}{% endblock %}
<body>
<aside>
    <a href="{% url 'home' %}" class="link-no-style">
        <div class="d-flex align-items-end">
        <img src="{% static 'main/img/logo-white.png' %}" alt="Логотип">
        <span class="logo">FootScore</span>
    </div>
    </a>
    <h3>Навигация</h3>
    <ul>
        <a href="{% url 'home' %}"><li><i class="fas fa-home"></i> Главная</li></a>
        <a href="{% url 'clubs_page' %}"><li><i class="fas fa-futbol"></i> Клубы</li></a>
        <a href="{% url 'ligs_page' %}"><li><i class="fas fa-file-alt"></i> Лиги</li></a>
        <a href="#"><li><i class="fas fa-users"></i> Игроки</li></a>
        <a href="{% url 'news_home' %}"><li><i class="fas fa-newspaper"></i> Новости</li></a>
        <a href="{% url 'matches_page' %}"><li><i class="fas fa-arrow-alt-circle-down"></i> Матчи</li></a>
        {% if perms.news.add_articles %}
        <a href="{% url 'add_new' %}"><li><button class="btn btn-info"><i class="fas fa-plus-circle"></i> Добавить новость</button></li></a>
        {% endif %}
        <br>
        {% if user.is_anonymous %}
        <a href="{% url 'login_user' %}"><li><i class="fas fa-door-open"></i> Войти</li></a>
        <a href="{% url 'reg_user' %}"><li><i class="fas fa-paper-plane"></i> Зарегистрироваться</li></a>
        {% else %}
        <a href="{% url 'logout_user' %}"><li><i class="fas fa-door-closed"></i> Выйти</li></a>
        {% endif %}
        {% if user.is_staff %}
        <a href="{% url 'admin:index' %}" target="_blank"><li><i class="fas fa-user-tie"></i> Админ панель</li></a>
        {% endif %}
    </ul>
</aside>
<main>
    {% block content %}
    {% endblock %}
</main>

</body>
</html>

webapp/main/templates/main/messages.html
{% if messages %}
<style>
    .success, .info, .warning, .error {
        display: block;
        position: relative;
        width: 100%;
        top: -1rem;
        text-align: center;
        line-height: 2rem;
        list-style: none;
        padding: 0.5rem 0;
    }
    .success {
        background: #35a36e;
    }
    .info {
        background: #3d6cbe;
    }
    .warning {
        background: #eacc47;
    }
    .error {
        background: #c23030;
    }
</style>
<ul>
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <li class="success">{{message}}</li>
        {% elif message.tags == 'warning' %}
            <li class="warning">{{message}}</li>
        {% elif message.tags == 'info' %}
            <li class="info">{{message}}</li>
        {% elif message.tags == 'error' %}
            <li class="error">{{message}}</li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}

webapp/main/templates/main/test.html
<p>Проверка</p>