webapp/clubs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('teams/', views.clubs, name='clubs_page'),
    path('teams/add/', views.add_team, name='clubs_add_page'),
    path('leagues/', views.ligs, name='ligs_page'),
    path('league/<int:liga_id>', views.league, name='liga_page'),
    path('leagues/add/', views.add_liga, name='ligs_add_page'),
    path('teams/favorite/', views.favorite_teams, name='clubs_favorite'),
    path('teams/<int:team_id>', views.club, name='club_page_players'),
    path('teams/<int:team_id>/check_favorite/', views.switch_favorite_team, name='switch_favorite_team'),
    path('teams/<int:team_id>/table', views.club_table, name='club_page_table'),
    path('teams/<int:team_id>/matches', views.club_matches, name='club_page_matches'),
    path('admin/player/add/<int:team_id>/', views.add_player_with_team, name='add_player_with_team'),
    path('admin/team_standings/add/<int:season_id>/<int:liga_id>', views.add_stand_with_season_and_liga,
         name='add_stand_with_season_and_liga'),
    path('admin/seasons/add/', views.add_season, name='add_season'),
    path('matches/', views.matches, name='matches_page')
]

webapp/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about')
]

webapp/webapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('clubs/', include('clubs.urls')),
    path('news/', include('news.urls')),
    path('auth/', include('authorization.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/clubs/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse


class Countries(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    short_name = models.CharField('Сокращенное название', max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Ligs(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('liga_page', kwargs={'liga_id': self.id})

    def get_table(self, season_id):
        season = Seasons.objects.get(id=season_id)
        table = TeamStandings.objects.filter(liga=self, season=season) \
            .order_by('-points', '-number_win', '-goal_differences')
        return table

    def get_matches(self):
        matches = Matches.objects.filter(liga=self).order_by('-date_match')
        return matches

    class Meta:
        verbose_name = 'Лига'
        verbose_name_plural = 'Лиги'


class Seasons(models.Model):
    begin_year = models.IntegerField(
        verbose_name='Начало',
        help_text='Введите год',
        validators=[MinValueValidator(1900), MaxValueValidator(2100)]
    )
    end_year = models.IntegerField(
        verbose_name='Конец',
        help_text='Введите год',
        validators=[MinValueValidator(1900), MaxValueValidator(2100)]
    )

    def __str__(self):
        return f'{self.begin_year}/{str(self.end_year)[-2:]}'

    class Meta:
        verbose_name = 'Сезон'
        verbose_name_plural = 'Сезоны'


class Positions(models.Model):
    short_name = models.CharField('Сокращенное название', max_length=10)
    full_name = models.CharField('Полное название', max_length=50)

    def __str__(self):
        return self.short_name

    class Meta:
        verbose_name = 'Позиция'
        verbose_name_plural = 'Позиции'


class WorkExperiense(models.Model):
    date_start = models.DateField('Начало')
    date_end = models.DateField('Конец', default=None, null=True, blank=True)

    def __str__(self):
        return f'Начало: {self.date_start} || Конец: {self.date_end}'

    class Meta:
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыты работы'


class Judges(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, max_length=50, blank=True)
    rating = models.DecimalField(max_digits=4, decimal_places=2)
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    work_experiense = models.ForeignKey(WorkExperiense, on_delete=models.PROTECT, verbose_name='Время работы')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    class Meta:
        verbose_name = 'Судья'
        verbose_name_plural = 'Судьи'


class Coaches(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, max_length=50, blank=True)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    work_experiense = models.ForeignKey(WorkExperiense, on_delete=models.PROTECT, verbose_name='Время работы')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренеры'


class Stadiums(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    address = models.TextField('Адрес')
    capacity = models.IntegerField(validators=[MinValueValidator(0)], verbose_name='Вместимость')
    history = models.TextField('История', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Стадион'
        verbose_name_plural = 'Стадионы'


class Teams(models.Model):
    full_name = models.CharField('Название', max_length=50, unique=True)
    short_name = models.CharField('Сокращенное название', max_length=20)
    city = models.CharField('Город', max_length=50)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    coach = models.OneToOneField(Coaches, on_delete=models.PROTECT, verbose_name='Тренер')
    stadium = models.ForeignKey(Stadiums, on_delete=models.PROTECT, verbose_name='Стадион')
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return self.short_name

    def get_absolute_url(self):
        return reverse('club_page_players', kwargs={'team_id': self.id})

    def get_players(self):
        return Players.objects.filter(team=self)

    def get_table(self):
        liga = Ligs.objects.filter(teamstandings__team=self).first()
        last_season = Seasons.objects.order_by('-begin_year').first()
        table = TeamStandings.objects.filter(liga=liga, season=last_season) \
            .order_by('-points', '-number_win', '-goal_differences')

        return table

    def get_matches(self):
        return Matches.objects.filter(Q(host_team=self) | Q(guest_team=self)).order_by('-date_match')

    def check_favorite(self, user):
        if user.is_anonymous:
            return False
        return FavoriteTeams.objects.filter(user=user, team=self).exists()

    class Meta:
        verbose_name = 'Команда'
        verbose_name_plural = 'Команды'


class Players(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, blank=True, max_length=50)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    position = models.ForeignKey(Positions, on_delete=models.PROTECT, verbose_name='Позиция')
    team = models.ForeignKey(Teams, on_delete=models.PROTECT, verbose_name='Команда')
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    def get_full_name(self):
        return f'{self.surname} {self.name} {self.secondname if self.secondname else ""}'

    class Meta:
        verbose_name = 'Игрок'
        verbose_name_plural = 'Игроки'


class Matches(models.Model):
    date_match = models.DateTimeField('Дата матча')
    goals_first_team = models.IntegerField(verbose_name='Голы первой команды', validators=[MinValueValidator(0)])
    goals_second_team = models.IntegerField(verbose_name='Голы второй команды', validators=[MinValueValidator(0)])
    minutes_left = models.IntegerField(verbose_name='Минут осталось', default=90)
    minutes_add = models.IntegerField(verbose_name='Минут добавлено', default=0)
    host_team = models.ForeignKey(
        Teams, on_delete=models.PROTECT,
        verbose_name='Команда хозяев', related_name='home_matches'
    )
    guest_team = models.ForeignKey(
        Teams, on_delete=models.PROTECT,
        verbose_name='Команда гостей', related_name='guest_matches'
    )
    liga = models.ForeignKey(Ligs, on_delete=models.PROTECT, verbose_name='Лига', related_name='matches')

    def __str__(self):
        return f'Матч: {self.host_team} {self.goals_first_team} : {self.goals_second_team} {self.guest_team}'

    def getTime(self):
        self_datetime = self.date_match
        return self_datetime.strftime('%H:%M')

    def getDate(self):
        self_datetime = self.date_match
        return self_datetime.strftime('%d.%m.%y')

    class Meta:
        verbose_name = 'Матч'
        verbose_name_plural = 'Матчи'


class TeamStandings(models.Model):
    team = models.ForeignKey(Teams, on_delete=models.PROTECT, verbose_name='Команда')
    season = models.ForeignKey(Seasons, on_delete=models.PROTECT, verbose_name='Сезон')
    points = models.IntegerField('Очки', default=0)
    number_win = models.IntegerField('Побед', default=0)
    number_loose = models.IntegerField('Поражений', default=0)
    number_draw = models.IntegerField('Ничей', default=0)
    goal_differences = models.IntegerField('Разница мячей', default=0)
    liga = models.ForeignKey(Ligs, on_delete=models.PROTECT, verbose_name='Лига')

    def __str__(self):
        return f'Очки: {self.points}'

    def get_number_matches(self):
        return self.number_win + self.number_loose + self.number_draw

    class Meta:
        verbose_name = 'Турнирная позиция'
        verbose_name_plural = 'Турнирные позиции'

        permissions = [
            ('can_change_results_team_standings', 'Возможность изменять статистические данные команды'),
        ]


class FavoriteTeams(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    team = models.ForeignKey(Teams, on_delete=models.CASCADE, verbose_name='Команда')

    def __str__(self):
        return f'Пользователь: {self.user}; Команда: {self.team}'

    class Meta:
        verbose_name = 'Избранные команды'
        verbose_name_plural = 'Избранная команда'

webapp/clubs/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class TeamFilterForm(forms.Form):
    name = forms.CharField(
        label='Команда',
        required=False,
        max_length=50,
        min_length=2,
    )
    country = forms.CharField(
        label='Страна',
        required=False,
    )


class TeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = ['full_name', 'short_name', 'city', 'image', 'coach', 'stadium', 'country']

    def clean_city(self):
        city = self.cleaned_data['city']

        if city[0].isupper():
            return city

        raise ValidationError('Город должен начинаться с заглавной буквы')


class LigaFilterForm(forms.Form):
    name = forms.CharField(
        label='Название',
        required=False,
        max_length=50,
    )
    country = forms.CharField(
        label='Страна',
        required=False,
        max_length=50,
    )


class LigaForm(forms.ModelForm):
    class Meta:
        model = Ligs
        fields = ['name', 'country']


class MatchFilter(forms.ModelForm):
    host_team = forms.CharField(
        label='Команда хозяев',
        required=False,
    )

    guest_team = forms.CharField(
        label='Команда гостей',
        required=False,
    )

    date_match = forms.DateTimeField(
        label='Дата матча',
        required=False,

    )

webapp/clubs/templates/clubs/add_liga.html
{% extends 'main/layout.html' %}

{% block title %}Создание лиги{% endblock %}

{% block content %}
{% load static %}
<div class="features">

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{message}}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <h1>Создание лиги</h1>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Создать</button>
    </form>
    <a href="{% url 'ligs_page'%}" class="btn btn-warning">Вернуться</a>
</div>
{% endblock %}

webapp/clubs/templates/clubs/add_team.html
{% extends 'main/layout.html' %}

{% block title %}Создание клуба{% endblock %}

{% block content %}
{% load static %}
<div class="features">
    <h1>Создание клуба</h1>

    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-success">Создать</button>
    </form>
    <a href="{% url 'clubs_page'%}" class="btn btn-warning">Вернуться</a>
</div>
{% endblock %}

webapp/clubs/templates/clubs/favorite_teams.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Клубы{% endblock %}
{% block links %}
<link rel="stylesheet" href="{% static 'clubs/css/teams.css' %}">
{% endblock %}

{% block content %}
<div class="features">
    <h2>Ваши любимые клубы</h2>
    {% for favorite in favorites %}
    <a href="{{ favorite.team.get_absolute_url }}" class="link_team">
        <div class="card" style="background-color: rgba(255, 255, 255, 0);">
            <div class="row g-0">
                <div class="col-md-4 d-flex align-items-center">
                    {% if favorite.team.image %}
                    <img src="{{ favorite.team.image.url }}" alt="Изображение" style="width: 200px; max-height: 180px">
                    {% else %}
                    <img src="{% static 'placeholder.png' %}" alt="Изображение" style="width: 200px; max-height: 180px">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h3 class="card-title">{{favorite.team.short_name}}</h3>
                        <p><b>Тренер: </b>{{favorite.team.coach}}</p>
                        <p><b>Город: </b>{{favorite.team.city}}</p>
                        <p><b>Стадион: </b>{{favorite.team.stadium}}</p>
                        <p><b>Страна: </b>{{favorite.team.country}}</p>
                    </div>
                </div>

            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}}

webapp/clubs/templates/clubs/liga.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Лиги{% endblock %}
{% block links%}
<link rel="stylesheet" href="{% static 'clubs/css/liga.css' %}">
{% endblock %}

{% block content %}
<div class="features">
    <div class="container position-relative">
        <h1>{{liga.name}}</h1>
        <a href="/admin/clubs/ligs/{{liga.id}}/change" target="_blank" style="position: absolute; right: 0; top: 1em;"
           class="btn btn-secondary">Изменить</a>
        <p>Страна: <b>{{liga.country}}</b></p>
        <form id="season_form" method="GET" class="text-start">
            <div class="form-group d-inline-block w-50">
                <label for="id_season">Сезон: </label>
                <div class="row w-75 align-items-center">
                    <div class="col-md-5">
                        <select name="id_season" id="id_season" class="form-select"
                                onchange="document.getElementById('season_form').submit()">
                            {% for season in seasons %}
                            <option value="{{season.id}}" {% if selectedSeasonId == season.id %} selected {%endif%}>
                                {{season}}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    {% if perms.clubs_add_season %}
                    <div class="col-md-7">
                        <a href="{% url 'add_season' %}" target="_blank">Добавить сезон</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </form>
        <h3 style="text-align: start">Таблица:</h3>
        {% if perms.clubs_add_teamstandings %}
        <div class="text-start mb-2">
            <a href="{% url 'add_stand_with_season_and_liga' selectedSeasonId liga.id %}" target="_blank"
               class="btn btn-secondary">Добавить позицию</a>
        </div>
        {% endif %}
        {% include 'clubs/fragments/table.html' with table=table %}
    </div>
</div>
{% endblock %}

webapp/clubs/templates/clubs/ligs.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Лиги{% endblock %}
{% block links%}
<link rel="stylesheet" href="{% static 'clubs/css/ligs.css' %}">
{% endblock %}

{% block content %}
<div class="features">

    {% include 'main/messages.html' %}

    <h1>Лиги</h1>
    {% if perms.clubs.add_ligs %}
    <a href="{% url 'ligs_add_page' %}" class="btn btn-info"><i class="fas fa-plus-circle"></i> Добавить лигу</a>
    {% endif %}

    <form class="form-col" method="get">
        {{ form }}
        <button class="btn btn-success" type="submit">Применить фильтр</button>
    </form>
    <div class="grid">
        {% for liga in ligs %}
        <a class="item-link" href="{{liga.get_absolute_url}}">
            <div class="grid-item">
                <h3 class="item-title">{{liga.name}}</h3>
                <div class="item-desc">
                    <p><b>Страна: </b>{{liga.country}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

webapp/clubs/templates/clubs/matches.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Матчи{% endblock %}
{% block links%}
<link rel="stylesheet" href="{% static 'clubs/css/liga.css' %}">
<link rel="stylesheet" href="{% static 'clubs/css/matches.css' %}">
{% endblock %}

{% block content %}
<div class="features">
    <h1>Матчи</h1>
    {{formLigaFilter}}
    <div class="container">
        {% for league in leagues %}
        <details class="liga-details">
            <summary>
                <span>{{league.name}} ({{league.country}})</span>
            </summary>
            <ul>
                {% if league.get_matches.count == 0 %}
                <li>
                    <p class="medium-header">Нет матчей</p>
                </li>
                {% endif %}
                {% for match in league.get_matches %}
                <li>
                    {% include 'clubs/fragments/match_card.html' with match=match %}
                </li>
                {% endfor %}
            </ul>
        </details>

        {% endfor %}
    </div>
</div>
{% endblock %}

webapp/clubs/templates/clubs/team_matches.html
{% extends 'main/layout.html' %}

{% block title %}Команда {{team.short_name}}{% endblock %}

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'clubs/css/team_matches.css' %}">
<div class="features">
    {% include 'clubs/fragments/team_page.html' with team=team %}
    <div>
        {% if team.get_matches.count == 0 %}
        <h3 style="margin-top: 50px">У клуба еще не было матчей</h3>
        {% else %}
        {% for match in team.get_matches %}
        {% include 'clubs/fragments/match_card.html' with match=match %}
        {% endfor %}
        {% endif %}
    </div>

    {% endblock %}
</div>

webapp/clubs/templates/clubs/team_players.html
{% extends 'main/layout.html' %}

{% block title %}Команда {{team.short_name}}{% endblock %}

{% block content %}
{% load static %}
<div class="features">
    {% include 'clubs/fragments/team_page.html' with team=team is_favorite=is_favorite %}
    <div>
        {% if perms.clubs.add_player %}
        <div class="text-start mt-2">
            <a class="btn btn-secondary" href="{% url 'add_player_with_team' team.id %}" target="_blank">Добавить игрока</a>
        </div>
        {% endif %}
        {% if team.get_players.count == 0 %}
        <h3 style="margin-top: 50px">У команды еще нет игроков</h3>
        {% endif %}
        {% for player in team.get_players %}
        <div class="card mt-2" style="max-width: 490px;">
            <div class="row g-0 d-flex align-items-center h-100">
                <div class="col-md-3 h-100">
                    {% if player.image %}
                    <img src="{{ player.image.url }}" style="max-height: 170px" class="card-img rounded-start"
                         alt="Изображение игрока">
                    {% else %}
                    <img src="{% static 'placeholder.png' %}" style="max-height: 170px" class="card-img rounded-start"
                         alt="Изображение игрока">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body position-relative">
                        <h5 class="card-title">{{player.get_full_name}}</h5>
                        <div style="text-align: left; margin-left: 10%">
                            <p><b>Позиция:</b> {{player.position}}</p>
                            <p class="card-text"><b>Возраст:</b> {{player.age}}</p>
                            <p class="card-text"><b>Страна:</b> {{player.country}}</p>
                        </div>
                        <div>
                            <a href="/admin/clubs/players/{{player.id}}/change" style="position: absolute; right: 0; bottom: 1em">Изменить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>

webapp/clubs/templates/clubs/team_table.html
{% extends 'main/layout.html' %}

{% block title %}Команда {{team.short_name}}{% endblock %}

{% block content %}
{% load static %}
<div class="features">
    {% include 'clubs/fragments/team_page.html' with team=team %}
    <div class="w-75 m-auto">
        {% if team.get_table.count == 0 %}
        <h3 style="margin-top: 50px">Команда не участвует ни в одной лиге</h3>
        {% else %}
        <h4 class="text-start">Сезон: {{team.get_table.first.season}}</h4>
        {% include 'clubs/fragments/table.html' with table=team.get_table %}
        {% endif %}
    </div>
    {% endblock %}
</div>

webapp/clubs/templates/clubs/teams.html
{% extends 'main/layout.html' %}
{% load static %}
{% block title %}Клубы{% endblock %}
{% block links %}
<link rel="stylesheet" href="{% static 'clubs/css/teams.css' %}">
{% endblock %}

{% block content %}
<div class="features">
    <h1>Клубы</h1>
    {% if perms.clubs.add_teams %}
    <a href="{% url 'clubs_add_page' %}" class="btn btn-info"><i class="fas fa-plus-circle"></i> Добавить команду</a>
    {% endif %}

    <form method="get" class="form-col">
        {{ form }}
        <button type="submit" class="btn btn-success">Применить фильтр</button>
    </form>

    {% if user.is_authenticated %}
    <div style="text-align: left; margin-bottom: 1em;">
        <a href="{% url 'clubs_favorite' %}">
            <button class="btn btn-danger"><i class="fas fa-heart"></i> Мои любимые клубы</button>
        </a>
    </div>
    {% endif %}
    {% for team in list_objects %}
    <a href="{{ team.get_absolute_url }}" class="link_team">
        <div class="card" style="background-color: rgba(255, 255, 255, 0);">
            <div class="row g-0">
                <div class="col-md-4">
                    {% if team.image %}
                    <img src="{{ team.image.url }}" alt="Изображение" style="width: 200px; max-height: 180px">
                    {% else %}
                    <img src="{% static 'placeholder.png' %}" alt="Изображение" style="width: 200px; max-height: 180px">
                    {% endif %}
                </div>
                <div class="col-md-8">
                    <div class="card-body-grid">
                        <h3 class="card-title">{{team.short_name}}</h3>
                        <p><b>Тренер: </b>{{team.coach}}</p>
                        <p><b>Город: </b>{{team.city}}</p>
                        <p><b>Стадион: </b>{{team.stadium}}</p>
                        <p><b>Страна: </b>{{team.country}}</p>
                    </div>
                </div>

            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}