webapp/clubs/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('teams/', views.clubs, name='clubs_page'),
    path('teams/add/', views.add_team, name='clubs_add_page'),
    path('leagues/', views.ligs, name='ligs_page'),
    path('league/<int:liga_id>', views.league, name='liga_page'),
    path('leagues/add/', views.add_liga, name='ligs_add_page'),
    path('teams/favorite/', views.favorite_teams, name='clubs_favorite'),
    path('teams/<int:team_id>', views.club, name='club_page_players'),
    path('teams/<int:team_id>/check_favorite/', views.switch_favorite_team, name='switch_favorite_team'),
    path('teams/<int:team_id>/table', views.club_table, name='club_page_table'),
    path('teams/<int:team_id>/matches', views.club_matches, name='club_page_matches'),
    path('admin/player/add/<int:team_id>/', views.add_player_with_team, name='add_player_with_team'),
    path('admin/team_standings/add/<int:season_id>/<int:liga_id>', views.add_stand_with_season_and_liga,
         name='add_stand_with_season_and_liga'),
    path('admin/seasons/add/', views.add_season, name='add_season'),
    path('matches/', views.matches, name='matches_page')
]

webapp/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about')
]

webapp/webapp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('main.urls')),
    path('clubs/', include('clubs.urls')),
    path('news/', include('news.urls')),
    path('auth/', include('authorization.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/clubs/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.db.models import Q
from django.urls import reverse


class Countries(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    short_name = models.CharField('Сокращенное название', max_length=10)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class Ligs(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('liga_page', kwargs={'liga_id': self.id})

    def get_table(self, season_id):
        season = Seasons.objects.get(id=season_id)
        table = TeamStandings.objects.filter(liga=self, season=season) \
            .order_by('-points', '-number_win', '-goal_differences')
        return table

    def get_matches(self):
        matches = Matches.objects.filter(liga=self).order_by('-date_match')
        return matches

    class Meta:
        verbose_name = 'Лига'
        verbose_name_plural = 'Лиги'


class Seasons(models.Model):
    begin_year = models.IntegerField(
        verbose_name='Начало',
        help_text='Введите год',
        validators=[MinValueValidator(1900), MaxValueValidator(2100)]
    )
    end_year = models.IntegerField(
        verbose_name='Конец',
        help_text='Введите год',
        validators=[MinValueValidator(1900), MaxValueValidator(2100)]
    )

    def __str__(self):
        return f'{self.begin_year}/{str(self.end_year)[-2:]}'

    class Meta:
        verbose_name = 'Сезон'
        verbose_name_plural = 'Сезоны'


class Positions(models.Model):
    short_name = models.CharField('Сокращенное название', max_length=10)
    full_name = models.CharField('Полное название', max_length=50)

    def __str__(self):
        return self.short_name

    class Meta:
        verbose_name = 'Позиция'
        verbose_name_plural = 'Позиции'


class WorkExperiense(models.Model):
    date_start = models.DateField('Начало')
    date_end = models.DateField('Конец', default=None, null=True, blank=True)

    def __str__(self):
        return f'Начало: {self.date_start} || Конец: {self.date_end}'

    class Meta:
        verbose_name = 'Опыт работы'
        verbose_name_plural = 'Опыты работы'


class Judges(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, max_length=50, blank=True)
    rating = models.DecimalField(max_digits=4, decimal_places=2)
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    work_experiense = models.ForeignKey(WorkExperiense, on_delete=models.PROTECT, verbose_name='Время работы')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    class Meta:
        verbose_name = 'Судья'
        verbose_name_plural = 'Судьи'


class Coaches(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, max_length=50, blank=True)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    work_experiense = models.ForeignKey(WorkExperiense, on_delete=models.PROTECT, verbose_name='Время работы')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренеры'


class Stadiums(models.Model):
    name = models.CharField('Название', max_length=50, unique=True)
    address = models.TextField('Адрес')
    capacity = models.IntegerField(validators=[MinValueValidator(0)], verbose_name='Вместимость')
    history = models.TextField('История', null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Стадион'
        verbose_name_plural = 'Стадионы'


class Teams(models.Model):
    full_name = models.CharField('Название', max_length=50, unique=True)
    short_name = models.CharField('Сокращенное название', max_length=20)
    city = models.CharField('Город', max_length=50)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    coach = models.OneToOneField(Coaches, on_delete=models.PROTECT, verbose_name='Тренер')
    stadium = models.ForeignKey(Stadiums, on_delete=models.PROTECT, verbose_name='Стадион')
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return self.short_name

    def get_absolute_url(self):
        return reverse('club_page_players', kwargs={'team_id': self.id})

    def get_players(self):
        return Players.objects.filter(team=self)

    def get_table(self):
        liga = Ligs.objects.filter(teamstandings__team=self).first()
        last_season = Seasons.objects.order_by('-begin_year').first()
        table = TeamStandings.objects.filter(liga=liga, season=last_season) \
            .order_by('-points', '-number_win', '-goal_differences')

        return table

    def get_matches(self):
        return Matches.objects.filter(Q(host_team=self) | Q(guest_team=self)).order_by('-date_match')

    def check_favorite(self, user):
        if user.is_anonymous:
            return False
        return FavoriteTeams.objects.filter(user=user, team=self).exists()

    class Meta:
        verbose_name = 'Команда'
        verbose_name_plural = 'Команды'


class Players(models.Model):
    name = models.CharField('Имя', max_length=50)
    surname = models.CharField('Фамилия', max_length=50)
    secondname = models.CharField('Отчество', null=True, blank=True, max_length=50)
    image = models.ImageField('Изображение', null=True, blank=True, upload_to='media')
    age = models.PositiveIntegerField(verbose_name='Возраст',
                                      validators=[MinValueValidator(18), MaxValueValidator(100)])
    position = models.ForeignKey(Positions, on_delete=models.PROTECT, verbose_name='Позиция')
    team = models.ForeignKey(Teams, on_delete=models.PROTECT, verbose_name='Команда')
    country = models.ForeignKey(Countries, on_delete=models.PROTECT, verbose_name='Страна')

    def __str__(self):
        return f'{self.surname} {self.name[0]}. {self.secondname[0] + "." if self.secondname else ""}'

    def get_full_name(self):
        return f'{self.surname} {self.name} {self.secondname if self.secondname else ""}'

    class Meta:
        verbose_name = 'Игрок'
        verbose_name_plural = 'Игроки'


class Matches(models.Model):
    date_match = models.DateTimeField('Дата матча')
    goals_first_team = models.IntegerField(verbose_name='Голы первой команды', validators=[MinValueValidator(0)])
    goals_second_team = models.IntegerField(verbose_name='Голы второй команды', validators=[MinValueValidator(0)])
    minutes_left = models.IntegerField(verbose_name='Минут осталось', default=90)
    minutes_add = models.IntegerField(verbose_name='Минут добавлено', default=0)
    host_team = models.ForeignKey(
        Teams, on_delete=models.PROTECT,
        verbose_name='Команда хозяев', related_name='home_matches'
    )
    guest_team = models.ForeignKey(
        Teams, on_delete=models.PROTECT,
        verbose_name='Команда гостей', related_name='guest_matches'
    )
    liga = models.ForeignKey(Ligs, on_delete=models.PROTECT, verbose_name='Лига', related_name='matches')

    def __str__(self):
        return f'Матч: {self.host_team} {self.goals_first_team} : {self.goals_second_team} {self.guest_team}'

    def getTime(self):
        self_datetime = self.date_match
        return self_datetime.strftime('%H:%M')

    def getDate(self):
        self_datetime = self.date_match
        return self_datetime.strftime('%d.%m.%y')

    class Meta:
        verbose_name = 'Матч'
        verbose_name_plural = 'Матчи'


class TeamStandings(models.Model):
    team = models.ForeignKey(Teams, on_delete=models.PROTECT, verbose_name='Команда')
    season = models.ForeignKey(Seasons, on_delete=models.PROTECT, verbose_name='Сезон')
    points = models.IntegerField('Очки', default=0)
    number_win = models.IntegerField('Побед', default=0)
    number_loose = models.IntegerField('Поражений', default=0)
    number_draw = models.IntegerField('Ничей', default=0)
    goal_differences = models.IntegerField('Разница мячей', default=0)
    liga = models.ForeignKey(Ligs, on_delete=models.PROTECT, verbose_name='Лига')

    def __str__(self):
        return f'Очки: {self.points}'

    def get_number_matches(self):
        return self.number_win + self.number_loose + self.number_draw

    class Meta:
        verbose_name = 'Турнирная позиция'
        verbose_name_plural = 'Турнирные позиции'

        permissions = [
            ('can_change_results_team_standings', 'Возможность изменять статистические данные команды'),
        ]


class FavoriteTeams(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    team = models.ForeignKey(Teams, on_delete=models.CASCADE, verbose_name='Команда')

    def __str__(self):
        return f'Пользователь: {self.user}; Команда: {self.team}'

    class Meta:
        verbose_name = 'Избранные команды'
        verbose_name_plural = 'Избранная команда'

webapp/clubs/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import *


class TeamFilterForm(forms.Form):
    name = forms.CharField(
        label='Команда',
        required=False,
        max_length=50,
        min_length=2,
    )
    country = forms.CharField(
        label='Страна',
        required=False,
    )


class TeamForm(forms.ModelForm):
    class Meta:
        model = Teams
        fields = ['full_name', 'short_name', 'city', 'image', 'coach', 'stadium', 'country']

    def clean_city(self):
        city = self.cleaned_data['city']

        if city[0].isupper():
            return city

        raise ValidationError('Город должен начинаться с заглавной буквы')


class LigaFilterForm(forms.Form):
    name = forms.CharField(
        label='Название',
        required=False,
        max_length=50,
    )
    country = forms.CharField(
        label='Страна',
        required=False,
        max_length=50,
    )


class LigaForm(forms.ModelForm):
    class Meta:
        model = Ligs
        fields = ['name', 'country']


class MatchFilter(forms.ModelForm):
    host_team = forms.CharField(
        label='Команда хозяев',
        required=False,
    )

    guest_team = forms.CharField(
        label='Команда гостей',
        required=False,
    )

    date_match = forms.DateTimeField(
        label='Дата матча',
        required=False,

    )

webapp/clubs/templates/clubs/fragments/match_card.html
<!doctype html>
<html lang="en">
<head>
    {% load static %}
    {% include 'main/fragments/links_css.html' %}
    <link rel="stylesheet" href="{% static 'clubs/css/team_matches.css' %}">
</head>
<body>
<div class="card card-match text-center mt-3">
    <div class="card-body">
        <div class="row">
            <div class="col-2 text-center border-right">
                <div class="row d-flex justify-content-center">{{match.getTime}}</div>
                <div class="row d-flex justify-content-center">{{match.getDate}}</div>
            </div>
            <div class="col-10 d-flex align-items-center">
                <div class="row w-100">
                    <div class="col-5 d-flex align-items-center justify-content-between">
                        <a href="{% url 'club_page_players' match.host_team.id %}">
                            <span style="margin-left: 3px">{{match.host_team.full_name}}</span>
                        </a>
                        {% if match.host_team.image %}
                        <img src="{{ match.host_team.image.url }}" height="50px" width="50px" class="rounded"
                             alt="Изображение команды">
                        {% else %}
                        <img src="{% static 'placeholder.png' %}" width="50px" height="50px" class="rounded-start"
                             alt="Изображение команды">
                        {% endif %}
                    </div>
                    <div class="col-2 d-flex align-items-center justify-content-center">
                        <b>{{match.goals_first_team}} - {{match.goals_second_team}}</b>
                    </div>
                    <div class="col-5 d-flex align-items-center justify-content-between">
                        {% if match.guest_team.image %}
                        <img src="{{ match.guest_team.image.url }}" height="50px" width="50px" class="rounded"
                             alt="Изображение команды">
                        {% else %}
                        <img src="{% static 'placeholder.png' %}" height="50px" width="50px"
                             class="rounded-start"
                             alt="Изображение команды">
                        {% endif %}
                        <a href="{% url 'club_page_players' match.guest_team.id %}">
                            <span style="margin-left: 3px">{{match.guest_team.full_name}}</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

webapp/clubs/templates/clubs/fragments/table.html
{% include 'main/fragments/links_css.html' %}
<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">#</th>
        <th scope="col">Команда</th>
        <th scope="col">Количество игр</th>
        <th scope="col">Побед</th>
        <th scope="col">Ничей</th>
        <th scope="col">Поражений</th>
        <th scope="col">Очков</th>
    </tr>
    </thead>
    <tbody>
    {% for table_team in table %}
    <tr class="{% if table_team.team == team %} table-active {%endif%}">
        <th scope="row">{{forloop.counter}}</th>
        <td>
            <a class="link-no-style" href="{% url 'club_page_players' table_team.team.id %}">{{table_team.team.full_name}}</a>
        </td>
        <td>{{ table_team.get_number_matches }}</td>
        <td>{{table_team.number_win }}</td>
        <td>{{table_team.number_draw }}</td>
        <td>{{table_team.number_loose }}</td>
        <td>{{table_team.points}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if table.count == 0 %}
<div class="h-25 d-flex justify-content-center align-items-center">
    <h3>Таблица пока пустая :(</h3>
</div>

{% endif %}

webapp/clubs/templates/clubs/fragments/team_page.html
{% load static %}
<link rel="stylesheet" href="{% static 'clubs/css/team_page.css' %}">
<div class="card mb-3" style="max-width: 80%;">
    <div class="row g-0">
        <div class="col-md-4">
            {% if team.image %}
            <img src="{{ team.image.url }}" class="img-fluid rounded-start" alt="Изображение">
            {% else %}
            <img src="{% static 'placeholder.png' %}" class="img-fluid rounded-start" alt="Изображение">
            {% endif %}
        </div>
        <div class="col-md-8">
            <div class="card-body position-relative">
<!--                <a href="#" class="favorite"><i class="fas fa-heart icon-large"></i></a>-->
                <a href="{% url 'switch_favorite_team' team.id %}" class="favorite">
                    {% if is_favorite %}
                    <i class="fas fa-heart icon-large"></i>
                    {% else %}
                    <i class="far fa-heart icon-large"></i>
                    {% endif %}
                </a>
                <h3 class="card-title">{{team.full_name}}</h3>
                <p class="card-text"><b>Тренер:</b> {{team.coach}}</p>
                <p class="card-text"><b>Стадион:</b> {{team.stadium}}</p>
                <p class="card-text"><b>Страна:</b> {{team.country}}</p>
                <p class="card-text"><b>Город:</b> {{team.city}}</p>
                {% if perms.clubs.change_teams %}
                <div class="card-footer">
                    <a href="/admin/clubs/teams/{{team.id}}/change" target="_blank">Изменить</a>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>
<ul class="nav nav-tabs">
    {% for item in menu %}
    <li class="nav-item">
        {% if route_name == item.url_name %}
        <a class="nav-link active" aria-current="page" href="{% url item.url_name team.id%}">{{item.title}}</a>
        {% else %}
        <a class="nav-link" style="color: var(--default-font-color)" aria-current="page"
           href="{% url item.url_name team.id%}">{{item.title}}</a>
        {% endif %}
    </li>
    {% endfor %}
</ul>